# Generated by Django 3.2 on 2021-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a type of musical instrument', max_length=100, unique=True, verbose_name='Type name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
