# Generated by Django 3.2 on 2021-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Plot')),
                ('type', models.ManyToManyField(help_text='Select a type for this instrument', to='music.Type')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
