# Generated by Django 3.2 on 2021-04-12 16:39

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=music.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.instrument')),
            ],
            options={
                'ordering': ['-last_update', 'type'],
            },
        ),
    ]
