# Generated by Django 3.2 on 2021-04-12 17:30

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210412_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.poster_path, verbose_name='Poster'),
        ),
    ]
